CREATE TABLE PM_WORKER (
  WORKER_ID       NUMBER PRIMARY KEY,
  WORKER_NAME     VARCHAR2(100) NOT NULL,
  PHONE           VARCHAR2(20),
  ADDRESS         VARCHAR2(255),
  STATUS          NUMBER(1) DEFAULT 1 NOT NULL,
  REMARKS         VARCHAR2(500),
  CREATED_BY      VARCHAR2(50),
  CREATED_DATE    DATE DEFAULT SYSDATE,
  UPDATED_BY      VARCHAR2(50),
  UPDATED_DATE    DATE
);

CREATE TABLE PM_WORKER_RATE_HISTORY (
  RATE_ID          NUMBER PRIMARY KEY,
  WORKER_ID        NUMBER NOT NULL,
  EFFECTIVE_FROM   DATE NOT NULL,
  EFFECTIVE_TO     DATE,
  RATE_PER_HOUR    NUMBER(10,2),
  RATE_PER_DAY     NUMBER(10,2),
  REMARKS          VARCHAR2(500),
  CREATED_BY       VARCHAR2(50),
  CREATED_DATE     DATE DEFAULT SYSDATE,
  CONSTRAINT CHK_RATE_RANGE CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM),
  CONSTRAINT CHK_RATE_VALUE CHECK (RATE_PER_HOUR IS NOT NULL OR RATE_PER_DAY IS NOT NULL)
);

CREATE TABLE PM_WORKER_ATTENDANCE (
  ATTENDANCE_ID    NUMBER PRIMARY KEY,
  WORKER_ID        NUMBER NOT NULL,
  PROJECT_ID       NUMBER NOT NULL,
  ATTENDANCE_DATE  DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  ENTRY_MODE       VARCHAR2(10),   -- 'TIME' or 'HOURS'
  START_TIME       VARCHAR2(5),             -- HH24:MI, only if ENTRY_MODE = 'TIME'
  END_TIME         VARCHAR2(5),
  CALC_BASIS       VARCHAR2(10),   -- 'HOUR' or 'DAY'
  HOURS_WORKED     NUMBER(5,2),
  DAYS_WORKED      NUMBER(3,1),
  REMARKS          VARCHAR2(500),
  CREATED_BY       VARCHAR2(50),
  CREATED_DATE     DATE DEFAULT SYSDATE,
  UPDATED_BY       VARCHAR2(50),
  UPDATED_DATE     DATE,

);



-- indexes

CREATE UNIQUE INDEX UX_RATE_ONE_OPEN ON PM_WORKER_RATE_HISTORY (
  CASE WHEN EFFECTIVE_TO IS NULL THEN WORKER_ID END
);

-- for filtering/joining rate history by worker
CREATE INDEX IX_RATE_WORKER ON PM_WORKER_RATE_HISTORY (WORKER_ID);

-- for attendance reports (by worker, by project, by date)
CREATE INDEX IX_ATT_WORKER  ON PM_WORKER_ATTENDANCE (WORKER_ID, ATTENDANCE_DATE);
CREATE INDEX IX_ATT_PROJECT ON PM_WORKER_ATTENDANCE (PROJECT_ID, ATTENDANCE_DATE);





-- ! invoice
CREATE TABLE PM_INVOICE (
  ID               NUMBER PRIMARY KEY,
  PROJECT_ID       NUMBER NOT NULL,
  AREA_TYPE        VARCHAR2(50) NOT NULL,
  AMOUNT           NUMBER(12,2) NOT NULL,

  PURCHASED_BY     VARCHAR2(20) NOT NULL,
  CONTRACTOR_ID    NUMBER,

  MATERIAL_TYPE    VARCHAR2(50),
  MATERIAL_OTHER   VARCHAR2(100),

  PAYMENT_METHOD   VARCHAR2(20) NOT NULL,
  PAYMENT_REF      VARCHAR2(100),

  RECEIPT_BLOB     BLOB,
  RECEIPT_FILENAME VARCHAR2(255),
  RECEIPT_MIME_TYPE VARCHAR2(100),
  RECEIPT_SIZE     NUMBER,

  STATUS           NUMBER(1) DEFAULT 1,

  CREATED_BY       NUMBER,
  CREATED_AT       DATE DEFAULT SYSDATE,

  CONSTRAINT CHK_PURCHASED_BY CHECK (PURCHASED_BY IN ('OWNER','CONTRACTOR')),
  CONSTRAINT CHK_PAYMENT_METHOD CHECK (PAYMENT_METHOD IN ('CREDIT_CARD','TRANSACTION')),
  CONSTRAINT CHK_RECEIPT_SIZE CHECK (RECEIPT_SIZE <= 1048576)
);


CREATE INDEX IDX_INVOICE_PROJECT ON PM_INVOICE(PROJECT_ID);
CREATE INDEX IDX_INVOICE_CONTRACTOR ON PM_INVOICE(CONTRACTOR_ID);





CREATE TABLE PM.PM_STATEMENT_INVOICE
(
  INVOICE_ID     NUMBER NOT NULL,
  PARENT_TYPE    VARCHAR2(10 BYTE) NOT NULL,   -- 'STAGING' or 'MAIN'
  PARENT_ID      NUMBER NOT NULL,              -- STAGING_ID or TXN_ID
  INVOICE_NO     VARCHAR2(100 BYTE),
  CREATION_DATE  DATE DEFAULT SYSDATE,
  CONSTRAINT PM_STATEMENT_INVOICE_PK PRIMARY KEY (INVOICE_ID)
);

CREATE TABLE PM.PM_STATEMENT_INVOICE_FILE
(
  FILE_ID        NUMBER NOT NULL,
  INVOICE_ID     NUMBER NOT NULL,
  FILE_DATA      BLOB,
  FILE_NAME      VARCHAR2(255 BYTE),
  FILE_TYPE      VARCHAR2(100 BYTE),
  FILE_SIZE      NUMBER,
  CREATION_DATE  DATE DEFAULT SYSDATE,
  CONSTRAINT PM_STATEMENT_INVOICE_FILE_PK PRIMARY KEY (FILE_ID)
);


CREATE INDEX PM_STMT_INV_PARENT_IDX
  ON PM.PM_STATEMENT_INVOICE (PARENT_TYPE, PARENT_ID);

CREATE INDEX PM_STMT_INV_FILE_INVOICE_IDX
  ON PM.PM_STATEMENT_INVOICE_FILE (INVOICE_ID);