CREATE TABLE PM_WORKER (
  WORKER_ID       NUMBER PRIMARY KEY,
  WORKER_NAME     VARCHAR2(100) NOT NULL,
  PHONE           VARCHAR2(20),
  ADDRESS         VARCHAR2(255),
  STATUS          NUMBER(1) DEFAULT 1 NOT NULL,
  REMARKS         VARCHAR2(500),
  CREATED_BY      VARCHAR2(50),
  CREATED_DATE    DATE DEFAULT SYSDATE,
  UPDATED_BY      VARCHAR2(50),
  UPDATED_DATE    DATE
);

CREATE TABLE PM_WORKER_RATE_HISTORY (
  RATE_ID          NUMBER PRIMARY KEY,
  WORKER_ID        NUMBER NOT NULL,
  EFFECTIVE_FROM   DATE NOT NULL,
  EFFECTIVE_TO     DATE,
  RATE_PER_HOUR    NUMBER(10,2),
  RATE_PER_DAY     NUMBER(10,2),
  REMARKS          VARCHAR2(500),
  CREATED_BY       VARCHAR2(50),
  CREATED_DATE     DATE DEFAULT SYSDATE,
  CONSTRAINT CHK_RATE_RANGE CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM),
  CONSTRAINT CHK_RATE_VALUE CHECK (RATE_PER_HOUR IS NOT NULL OR RATE_PER_DAY IS NOT NULL)
);

CREATE TABLE PM_WORKER_ATTENDANCE (
  ATTENDANCE_ID    NUMBER PRIMARY KEY,
  WORKER_ID        NUMBER NOT NULL,
  PROJECT_ID       NUMBER NOT NULL,
  ATTENDANCE_DATE  DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  ENTRY_MODE       VARCHAR2(10),   -- 'TIME' or 'HOURS'
  START_TIME       VARCHAR2(5),             -- HH24:MI, only if ENTRY_MODE = 'TIME'
  END_TIME         VARCHAR2(5),
  CALC_BASIS       VARCHAR2(10),   -- 'HOUR' or 'DAY'
  HOURS_WORKED     NUMBER(5,2),
  DAYS_WORKED      NUMBER(3,1),
  REMARKS          VARCHAR2(500),
  CREATED_BY       VARCHAR2(50),
  CREATED_DATE     DATE DEFAULT SYSDATE,
  UPDATED_BY       VARCHAR2(50),
  UPDATED_DATE     DATE,

  APPROVAL_STATUS  VARCHAR2(10) DEFAULT 'PENDING' NOT NULL,
  APPROVED_BY      VARCHAR2(50),
  APPROVED_DATE    DATE,
  CONSTRAINT CHK_ATTENDANCE_APPROVAL CHECK (APPROVAL_STATUS IN ('PENDING','APPROVED'))

);



-- indexes

CREATE UNIQUE INDEX UX_RATE_ONE_OPEN ON PM_WORKER_RATE_HISTORY (
  CASE WHEN EFFECTIVE_TO IS NULL THEN WORKER_ID END
);

-- for filtering/joining rate history by worker
CREATE INDEX IX_RATE_WORKER ON PM_WORKER_RATE_HISTORY (WORKER_ID);

-- for attendance reports (by worker, by project, by date)
CREATE INDEX IX_ATT_WORKER  ON PM_WORKER_ATTENDANCE (WORKER_ID, ATTENDANCE_DATE);
CREATE INDEX IX_ATT_PROJECT ON PM_WORKER_ATTENDANCE (PROJECT_ID, ATTENDANCE_DATE);





-- ! invoice
CREATE TABLE PM_INVOICE (
  ID               NUMBER PRIMARY KEY,
  PROJECT_ID       NUMBER NOT NULL,
  AREA_TYPE        VARCHAR2(50) NOT NULL,
  AMOUNT           NUMBER(12,2) NOT NULL,

  PURCHASED_BY     VARCHAR2(20) NOT NULL,
  CONTRACTOR_ID    NUMBER,

  MATERIAL_TYPE    VARCHAR2(50),
  MATERIAL_OTHER   VARCHAR2(100),

  PAYMENT_METHOD   VARCHAR2(20) NOT NULL,
  PAYMENT_REF      VARCHAR2(100),

  RECEIPT_BLOB     BLOB,
  RECEIPT_FILENAME VARCHAR2(255),
  RECEIPT_MIME_TYPE VARCHAR2(100),
  RECEIPT_SIZE     NUMBER,

  STATUS           NUMBER(1) DEFAULT 1,

  CREATED_BY       NUMBER,
  CREATED_AT       DATE DEFAULT SYSDATE,

  CONSTRAINT CHK_PURCHASED_BY CHECK (PURCHASED_BY IN ('OWNER','CONTRACTOR')),
  CONSTRAINT CHK_PAYMENT_METHOD CHECK (PAYMENT_METHOD IN ('CREDIT_CARD','TRANSACTION')),
  CONSTRAINT CHK_RECEIPT_SIZE CHECK (RECEIPT_SIZE <= 1048576)
);


CREATE INDEX IDX_INVOICE_PROJECT ON PM_INVOICE(PROJECT_ID);
CREATE INDEX IDX_INVOICE_CONTRACTOR ON PM_INVOICE(CONTRACTOR_ID);





CREATE TABLE PM.PM_STATEMENT_INVOICE
(
  INVOICE_ID     NUMBER NOT NULL,
  PARENT_TYPE    VARCHAR2(10 BYTE) NOT NULL,   -- 'STAGING' or 'MAIN'
  PARENT_ID      NUMBER NOT NULL,              -- STAGING_ID or TXN_ID
  INVOICE_NO     VARCHAR2(100 BYTE),
  CREATION_DATE  DATE DEFAULT SYSDATE,
  CONSTRAINT PM_STATEMENT_INVOICE_PK PRIMARY KEY (INVOICE_ID)
);

CREATE TABLE PM.PM_STATEMENT_INVOICE_FILE
(
  FILE_ID        NUMBER NOT NULL,
  INVOICE_ID     NUMBER NOT NULL,
  FILE_DATA      BLOB,
  FILE_NAME      VARCHAR2(255 BYTE),
  FILE_TYPE      VARCHAR2(100 BYTE),
  FILE_SIZE      NUMBER,
  CREATION_DATE  DATE DEFAULT SYSDATE,
  CONSTRAINT PM_STATEMENT_INVOICE_FILE_PK PRIMARY KEY (FILE_ID)
);


CREATE INDEX PM_STMT_INV_PARENT_IDX
  ON PM.PM_STATEMENT_INVOICE (PARENT_TYPE, PARENT_ID);

CREATE INDEX PM_STMT_INV_FILE_INVOICE_IDX
  ON PM.PM_STATEMENT_INVOICE_FILE (INVOICE_ID);




  -- ! todo table
  -- Sequence
CREATE SEQUENCE PM.TODO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Table
CREATE TABLE PM.PM_TODO
(
  TODO_ID       NUMBER            NOT NULL,
  TITLE         VARCHAR2(200 BYTE) NOT NULL,
  DESCRIPTION   VARCHAR2(1000 BYTE),
  STATUS        VARCHAR2(20 BYTE) DEFAULT 'TODO' NOT NULL, -- TODO | DONE | REVIEWED
  PRIORITY      NUMBER            DEFAULT 2,               -- optional: 1=high,2=med,3=low
  DUE_DATE      DATE,
  REMARKS       VARCHAR2(1000 BYTE),
  SORT_ORDER    NUMBER,
  CREATED_BY    NUMBER,
  CREATED_DATE  DATE              DEFAULT SYSDATE,
  UPDATED_BY    NUMBER,
  UPDATED_DATE  DATE              DEFAULT SYSDATE
)
TABLESPACE USERS;

-- Primary Key
ALTER TABLE PM.PM_TODO ADD (
  CONSTRAINT PM_TODO_PK PRIMARY KEY (TODO_ID)
  USING INDEX TABLESPACE USERS
  ENABLE VALIDATE);

-- Status check constraint
ALTER TABLE PM.PM_TODO ADD (
  CONSTRAINT PM_TODO_STATUS_CHK
  CHECK (STATUS IN ('TODO','DONE','REVIEWED')));

-- Autonumber trigger
CREATE OR REPLACE TRIGGER PM.PM_TODO_TRG
BEFORE INSERT ON PM.PM_TODO
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  :new.TODO_ID := PM.TODO_SEQ.NEXTVAL;
END PM_TODO_TRG;
/










--------------------------------------------------------------------------
-- NOTIFICATIONS (generic, reusable across all modules)
--------------------------------------------------------------------------

CREATE TABLE notifications (
    notification_id   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id            NUMBER        NOT NULL,           -- PM.USERS.ID — recipient
    type               VARCHAR2(40)  NOT NULL,           -- e.g. 'TICKET_COMMENT', 'TICKET_ASSIGNED', 'STATEMENT_APPROVED'
    title              VARCHAR2(200),
    message            VARCHAR2(500),
    entity_type        VARCHAR2(30),                      -- 'TICKET', 'PROJECT', 'CONTRACTOR', 'STATEMENT', 'INVOICE', etc.
    entity_id          NUMBER,                             -- id within that entity_type's table
    link               VARCHAR2(255),                      -- frontend route, e.g. /dashboard/tickets/5
    is_read            CHAR(1)       DEFAULT 'N' NOT NULL CHECK (is_read IN ('Y','N')),
    created_at         TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_notifications_user       ON notifications(user_id);
CREATE INDEX idx_notifications_user_read  ON notifications(user_id, is_read);
CREATE INDEX idx_notifications_entity     ON notifications(entity_type, entity_id);
CREATE INDEX idx_notifications_created    ON notifications(created_at);