CREATE TABLE PM_WORKER (
  WORKER_ID       NUMBER PRIMARY KEY,
  WORKER_NAME     VARCHAR2(100) NOT NULL,
  PHONE           VARCHAR2(20),
  ADDRESS         VARCHAR2(255),
  STATUS          NUMBER(1) DEFAULT 1 NOT NULL,
  REMARKS         VARCHAR2(500),
  CREATED_BY      VARCHAR2(50),
  CREATED_DATE    DATE DEFAULT SYSDATE,
  UPDATED_BY      VARCHAR2(50),
  UPDATED_DATE    DATE
);

CREATE TABLE PM_WORKER_RATE_HISTORY (
  RATE_ID          NUMBER PRIMARY KEY,
  WORKER_ID        NUMBER NOT NULL,
  EFFECTIVE_FROM   DATE NOT NULL,
  EFFECTIVE_TO     DATE,
  RATE_PER_HOUR    NUMBER(10,2),
  RATE_PER_DAY     NUMBER(10,2),
  REMARKS          VARCHAR2(500),
  CREATED_BY       VARCHAR2(50),
  CREATED_DATE     DATE DEFAULT SYSDATE,
  CONSTRAINT CHK_RATE_RANGE CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM),
  CONSTRAINT CHK_RATE_VALUE CHECK (RATE_PER_HOUR IS NOT NULL OR RATE_PER_DAY IS NOT NULL)
);

CREATE TABLE PM_WORKER_ATTENDANCE (
  ATTENDANCE_ID    NUMBER PRIMARY KEY,
  WORKER_ID        NUMBER NOT NULL,
  PROJECT_ID       NUMBER NOT NULL,
  ATTENDANCE_DATE  DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  ENTRY_MODE       VARCHAR2(10),   -- 'TIME' or 'HOURS'
  START_TIME       VARCHAR2(5),             -- HH24:MI, only if ENTRY_MODE = 'TIME'
  END_TIME         VARCHAR2(5),
  CALC_BASIS       VARCHAR2(10) NOT NULL,   -- 'HOUR' or 'DAY'
  HOURS_WORKED     NUMBER(5,2),
  DAYS_WORKED      NUMBER(3,1),
  REMARKS          VARCHAR2(500),
  CREATED_BY       VARCHAR2(50),
  CREATED_DATE     DATE DEFAULT SYSDATE,
  CONSTRAINT CHK_ENTRY_MODE CHECK (ENTRY_MODE IN ('TIME','HOURS')),
  CONSTRAINT CHK_CALC_BASIS CHECK (CALC_BASIS IN ('HOUR','DAY'))
);



-- indexes

CREATE UNIQUE INDEX UX_RATE_ONE_OPEN ON PM_WORKER_RATE_HISTORY (
  CASE WHEN EFFECTIVE_TO IS NULL THEN WORKER_ID END
);

-- for filtering/joining rate history by worker
CREATE INDEX IX_RATE_WORKER ON PM_WORKER_RATE_HISTORY (WORKER_ID);

-- for attendance reports (by worker, by project, by date)
CREATE INDEX IX_ATT_WORKER  ON PM_WORKER_ATTENDANCE (WORKER_ID, ATTENDANCE_DATE);
CREATE INDEX IX_ATT_PROJECT ON PM_WORKER_ATTENDANCE (PROJECT_ID, ATTENDANCE_DATE);