import { poolExecute } from "../../config/db.js";
import oracledb from "oracledb";

// ─── PM_OWNER_INFO ────────────────────────────────────────────────────────────

/**
 * GET all owner info rows, joining PM_PROJECT for project name.
 */
export async function getAllOwnerInfo() {
  const sql = `
    SELECT
      oi.ID,
      oi.O_NAME,
      oi.ADDRESS,
      oi.SUBURB,
      oi.POSTCODE,
      oi.STATE,
      oi.EMAIL,
      oi.PHONE,
      oi.PROJECT_ID,
      p.P_NAME   AS PROJECT_NAME,
      oi.CREATED_BY,
      oi.UPDATED_BY,
      oi.ENTRY_DATE,
      oi.UPDATED_DATE
    FROM PM_OWNER_INFO oi
    LEFT JOIN PM_PROJECT p ON p.P_ID = oi.PROJECT_ID
    ORDER BY oi.ID
  `;
  const result = await poolExecute(sql, {}, { outFormat: oracledb.OUT_FORMAT_OBJECT });
  return result.rows;
}

/**
 * GET single owner info row by ID.
 */
export async function getOwnerInfoById(id) {
  const sql = `
    SELECT
      oi.ID,
      oi.O_NAME,
      oi.ADDRESS,
      oi.SUBURB,
      oi.POSTCODE,
      oi.STATE,
      oi.EMAIL,
      oi.PHONE,
      oi.PROJECT_ID,
      p.P_NAME   AS PROJECT_NAME,
      oi.CREATED_BY,
      oi.UPDATED_BY,
      oi.ENTRY_DATE,
      oi.UPDATED_DATE
    FROM PM_OWNER_INFO oi
    LEFT JOIN PM_PROJECT p ON p.P_ID = oi.PROJECT_ID
    WHERE oi.ID = :id
  `;
  const result = await poolExecute(
    sql,
    { id },
    { outFormat: oracledb.OUT_FORMAT_OBJECT }
  );
  return result.rows[0] ?? null;
}

/**
 * GET all owner info rows for a specific project.
 */
export async function getOwnerInfoByProjectId(projectId) {
  const sql = `
    SELECT
      oi.ID,
      oi.O_NAME,
      oi.ADDRESS,
      oi.SUBURB,
      oi.POSTCODE,
      oi.STATE,
      oi.EMAIL,
      oi.PHONE,
      oi.PROJECT_ID,
      p.P_NAME   AS PROJECT_NAME,
      oi.CREATED_BY,
      oi.UPDATED_BY,
      oi.ENTRY_DATE,
      oi.UPDATED_DATE
    FROM PM_OWNER_INFO oi
    LEFT JOIN PM_PROJECT p ON p.P_ID = oi.PROJECT_ID
    WHERE oi.PROJECT_ID = :projectId
    ORDER BY oi.ID
  `;
  const result = await poolExecute(
    sql,
    { projectId },
    { outFormat: oracledb.OUT_FORMAT_OBJECT }
  );
  return result.rows;
}

/**
 * CREATE a new PM_OWNER_INFO row.
 * ID is generated by a sequence — adjust SEQ name to match your DB.
 */
export async function createOwnerInfo(data) {
  const {
    oName,
    address,
    suburb,
    postcode,
    state,
    email,
    phone,
    projectId,
    createdBy,
    updatedBy,
  } = data;

  const sql = `
    INSERT INTO PM_OWNER_INFO (
      
      O_NAME,
      ADDRESS,
      SUBURB,
      POSTCODE,
      STATE,
      EMAIL,
      PHONE,
      PROJECT_ID,
      CREATED_BY,
      UPDATED_BY,
      ENTRY_DATE,
      UPDATED_DATE
    ) VALUES (
      
      :oName,
      :address,
      :suburb,
      :postcode,
      :state,
      :email,
      :phone,
      :projectId,
      :createdBy,
      :updatedBy,
      SYSDATE,
      SYSDATE
    )
    RETURNING ID INTO :newId
  `;

  const binds = {
    oName:     oName     ?? null,
    address:   address   ?? null,
    suburb:    suburb    ?? null,
    postcode:  postcode  ?? null,
    state:     state     ?? null,
    email:     email     ?? null,
    phone:     phone     ?? null,
    projectId: projectId ?? null,
    createdBy: createdBy ?? null,
    updatedBy: updatedBy ?? null,
    newId: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER },
  };

  const result = await poolExecute(sql, binds, { autoCommit: true });
  return { id: result.outBinds.newId[0] };
}

/**
 * UPDATE an existing PM_OWNER_INFO row.
 */
export async function updateOwnerInfo(id, data) {
  const {
    oName,
    address,
    suburb,
    postcode,
    state,
    email,
    phone,
    projectId,
    updatedBy,
  } = data;

  const sql = `
    UPDATE PM_OWNER_INFO
    SET
      O_NAME       = :oName,
      ADDRESS      = :address,
      SUBURB       = :suburb,
      POSTCODE     = :postcode,
      STATE        = :state,
      EMAIL        = :email,
      PHONE        = :phone,
      PROJECT_ID   = :projectId,
      UPDATED_BY   = :updatedBy,
      UPDATED_DATE = SYSDATE
    WHERE ID = :id
  `;

  const result = await poolExecute(
    sql,
    { oName, address, suburb, postcode, state, email, phone, projectId, updatedBy, id },
    { autoCommit: true }
  );
  return result.rowsAffected;
}

/**
 * DELETE a PM_OWNER_INFO row.
 */
export async function deleteOwnerInfo(id) {
  const sql = `DELETE FROM PM_OWNER_INFO WHERE ID = :id`;
  const result = await poolExecute(sql, { id }, { autoCommit: true });
  return result.rowsAffected;
}

// ─── PM_PROJECT lookup (for dropdown) ────────────────────────────────────────

/**
 * GET all projects — used to populate the project dropdown in the Owner form.
 */
export async function getAllProjects() {
  const sql = `
    SELECT P_ID AS ID, P_NAME AS NAME
    FROM PM_PROJECT
    ORDER BY P_ID
  `;
  const result = await poolExecute(sql, {}, { outFormat: oracledb.OUT_FORMAT_OBJECT });
  return result.rows;
}