import { poolExecute } from "../../config/db.js";
import oracledb from "oracledb";

const TABLE = "PM_CALENDAR_T";

// ─── GET ALL ───────────────────────────────────────────────────────────────────
export async function getAllCalendarDays({ monthId } = {}) {
  let sql = `
    SELECT
      DAY_ID,
      TO_CHAR(DAY, 'YYYY-MM-DD')                          AS DAY,
      HOLIDAY_DESCRIPTION,
      WORKING_STATUS,
      LAST_UPDATED_BY,
      TO_CHAR(LAST_UPDATED_DATE, 'YYYY-MM-DD HH24:MI:SS') AS LAST_UPDATED_DATE,
      MONTH_ID,
      DAY_NAME
    FROM ${TABLE}
  `;
  const binds = {};

  if (monthId) {
    sql += ` WHERE MONTH_ID = :monthId`;
    binds.monthId = Number(monthId);
  }

  sql += ` ORDER BY DAY ASC`;

  const result = await poolExecute(sql, binds, { outFormat: oracledb.OUT_FORMAT_OBJECT });
  return result.rows;
}

// ─── GET BY ID ─────────────────────────────────────────────────────────────────
export async function getCalendarDayById(dayId) {
  const sql = `
    SELECT
      DAY_ID,
      TO_CHAR(DAY, 'YYYY-MM-DD')                          AS DAY,
      HOLIDAY_DESCRIPTION,
      WORKING_STATUS,
      LAST_UPDATED_BY,
      TO_CHAR(LAST_UPDATED_DATE, 'YYYY-MM-DD HH24:MI:SS') AS LAST_UPDATED_DATE,
      MONTH_ID,
      DAY_NAME
    FROM ${TABLE}
    WHERE DAY_ID = :dayId
  `;
  const result = await poolExecute(
    sql,
    { dayId: Number(dayId) },
    { outFormat: oracledb.OUT_FORMAT_OBJECT }
  );
  return result.rows[0] ?? null;
}

// ─── CREATE ────────────────────────────────────────────────────────────────────
// DAY_ID is auto-generated by DB trigger — we use RETURNING to get it back
export async function createCalendarDay(data) {
  const { day, holidayDescription, workingStatus, lastUpdatedBy, monthId, dayName } = data;

  const sql = `
    INSERT INTO ${TABLE} (
      DAY,
      HOLIDAY_DESCRIPTION,
      WORKING_STATUS,
      LAST_UPDATED_BY,
      LAST_UPDATED_DATE,
      MONTH_ID,
      DAY_NAME
    ) VALUES (
      TO_DATE(:day, 'YYYY-MM-DD'),
      :holidayDescription,
      :workingStatus,
      :lastUpdatedBy,
      SYSDATE,
      :monthId,
      :dayName
    )
    RETURNING DAY_ID INTO :newDayId
  `;

  const result = await poolExecute(
    sql,
    {
      day,
      holidayDescription: holidayDescription ?? null,
      workingStatus:      workingStatus      ?? null,
      lastUpdatedBy:      lastUpdatedBy      ?? null,
      monthId:            monthId ? Number(monthId) : null,
      dayName:            dayName            ?? null,
      newDayId:           { dir: oracledb.BIND_OUT, type: oracledb.NUMBER },
    },
    { autoCommit: true }
  );

  const newId = result.outBinds.newDayId[0];
  return getCalendarDayById(newId);
}

// ─── UPDATE ────────────────────────────────────────────────────────────────────
export async function updateCalendarDay(dayId, data) {
  const existing = await getCalendarDayById(dayId);
  if (!existing) return null;

  const { day, holidayDescription, workingStatus, lastUpdatedBy, monthId, dayName } = data;

  const sql = `
    UPDATE ${TABLE}
    SET
      DAY                 = TO_DATE(:day, 'YYYY-MM-DD'),
      HOLIDAY_DESCRIPTION = :holidayDescription,
      WORKING_STATUS      = :workingStatus,
      LAST_UPDATED_BY     = :lastUpdatedBy,
      LAST_UPDATED_DATE   = SYSDATE,
      MONTH_ID            = :monthId,
      DAY_NAME            = :dayName
    WHERE DAY_ID = :dayId
  `;

  await poolExecute(
    sql,
    {
      day,
      holidayDescription: holidayDescription ?? null,
      workingStatus:      workingStatus      ?? null,
      lastUpdatedBy:      lastUpdatedBy      ?? null,
      monthId:            monthId ? Number(monthId) : null,
      dayName:            dayName            ?? null,
      dayId:              Number(dayId),
    },
    { autoCommit: true }
  );

  return getCalendarDayById(dayId);
}

// ─── PATCH WORKING STATUS ──────────────────────────────────────────────────────
export async function patchWorkingStatus(dayId, workingStatus, lastUpdatedBy) {
  const existing = await getCalendarDayById(dayId);
  if (!existing) return null;

  await poolExecute(
    `UPDATE ${TABLE}
     SET WORKING_STATUS    = :workingStatus,
         LAST_UPDATED_BY   = :lastUpdatedBy,
         LAST_UPDATED_DATE = SYSDATE
     WHERE DAY_ID = :dayId`,
    {
      workingStatus,
      lastUpdatedBy: lastUpdatedBy ?? null,
      dayId:         Number(dayId),
    },
    { autoCommit: true }
  );

  return getCalendarDayById(dayId);
}

// ─── DELETE ────────────────────────────────────────────────────────────────────
export async function deleteCalendarDay(dayId) {
  const existing = await getCalendarDayById(dayId);
  if (!existing) return null;

  await poolExecute(
    `DELETE FROM ${TABLE} WHERE DAY_ID = :dayId`,
    { dayId: Number(dayId) },
    { autoCommit: true }
  );

  return existing;
}

// ─── BULK CREATE ───────────────────────────────────────────────────────────────
export async function bulkCreateCalendarDays(days) {
  const results = [];
  for (const d of days) {
    const created = await createCalendarDay(d);
    results.push(created);
  }
  return results;
}